up_1: 1
form:
  text_area_rows: 8
department:
  validates:
    name:
      max: 30
    description:
      max: 5000
users:
  per: 10
dish_types:
  format_date: "%d/%m/%Y"
  format_time: "%H:%M"
email_regex: !ruby/regexp /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
admin_customer:
  per_page: 5
user:
  name:
    max_length: 50
  email:
    max_length: 200
  address:
    max_length: 255
  phone:
    min_length: 10
    max_length: 12
  password:
    min_length: 6
dishes:
  per_page: 4
  status: "in_stock"
  price:
    max_length: 10
    min_value: 0
manage_tables:
  format_date: "On %I:%M%p %m/%d/%Y"
  per_page: 8
orders:
  per_page: 5
  complete: "complete"
table:
  numb: 20
  dish: 4
role:
  admin: "admin"
  default_password: "Ngvanhao123"
phone: "0123456789"
birthday: "2020-07-13"
